;	Archivo para introducir el formato de los valores, el único
;	Realmente importante es "f" porque indica si el valor es fecha
;	Sino es una fecha, entonces se usará double como tipo de valor predeterminado
;	Los tipos posibles de valor son
;	f 	- 	fecha (aaaa-mm-dd)
;	d	- 	double
;	c	- 	char
;	i	-	int
;	SEPARADOR , indica que los valores estarán separados por comas
;	SEPARADOR . indica que estarán separados por puntos etc.d
;	ETIQUETAS = "fecha", "algo más", "otra cosa" <<-- indica las etiquetas que se asignarán a cada columna
; 	Sino se pone "SEPARADOR #" entonces se asumirá que están separados por tabuladores/espacios
; 	En el caso predeterminado se espera:
; 	Fecha - precipitación - evaporación - temp. Máxima - temp. Mínima
ETIQUETAS = "Fecha"  "Precipitación"  "Evaporación"  "Temp. Máxima"  "Temp. Mínima"
;	Si el separador se queda comentado, el separador será "\\s+" (Espacios o tabuladores)
;	SEPARADOR = ,
FORMATO = f d d d d
;	El formato -DEBE- estar separado con el mismo separador si se indica el separador antes
;	i.e.
;	SEPARADOR = ,
;	FORMATO = f,d,d,d,d  <<-- sería el formato correcto